show_excerpts: true
title: Roald Ruiter
description: >- # this means to ignore newlines until "baseurl:"
  Personal projects and thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  roald87
linkedin_username: roaldruiter

texture:
  title: Roald Ruiter
  tagline: Personal projects and thoughts.
  date_format: "%b %-d, %Y"
  style: black
  
  showNav: true
  navigation:
    - title: Home
      url: "/"
    - title: About
      url: "/about"
    - title: Tags
      url: "/tags" 

  social_links:
    github:  roald87
    linkedIn: in/roaldruiter
    rss: rss

# Build settings
markdown: kramdown
remote_theme: thelehhman/texture
plugins:
  - jekyll-feed
  - jemoji
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
